export const CATEGORIES = [
  { title: 'Business / Money', value: 'business-money' },
  { title: 'Food', value: 'food' },
  { title: 'Health / Fitness', value: 'health-fitness' },
  { title: 'Hobbies / Interests', value: 'hobbies-interests' },
  { title: 'Home', value: 'home' },
  { title: 'Family / Relationship', value: 'family-relationship' },
  { title: 'Geography', value: 'geography' },
  { title: 'Nature / Environment', value: 'nature-environment' },
  { title: 'People / Society', value: 'people-society' },
  { title: 'Politics / Law', value: 'politics-law' },
  { title: 'Science / Technology', value: 'science-technology' },
  { title: 'Sports / Games', value: 'sports-games' },
  { title: 'Travel', value: 'travel' },
  { title: ' Transportation', value: 'transportation' },
]
